# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
           java-version: 1.8
     
      - name: set Java
        uses: actions/setup-java@v2
        with:
         distribution: 'zulu'
         java-version: '11'
      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        
      - name: start build runner to generate
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
        

      - name: Run tests
        run: flutter test
        
        
      - name: build Apk
        run: flutter build apk --release
        
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: build/app/outputs/apk/release/app-release.apk
